name: example
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  cloud_functions:
  cupertino_icons:
  firebase_auth:
  firebase_core:
  firestore_ref:
    path: ..
  flutter:
    sdk: flutter
  flutter_state_notifier:
  freezed_annotation:
  provider:
  recase:
  state_notifier:
  subscription_holder: any
dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any
  pedantic_mono: any
flutter:
  uses-material-design: true
