name: example
description: A new Flutter application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
dependencies:
  cloud_firestore:
  cloud_functions:
  cupertino_icons:
  firebase_auth:
  firebase_core:
  firebase_storage:
  firestore_ref:
    path: ..
  flutter:
    sdk: flutter
  flutter_hooks:
  freezed_annotation:
  hooks_riverpod:
  recase:
  rxdart:
  state_notifier:
  subscription_holder:
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  pedantic_mono:
flutter:
  uses-material-design: true
