name: example
description: A new Flutter application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  cloud_functions:
  cupertino_icons:
  firebase_auth:
  firebase_core:
  firestore_ref:
    path: ..
  flutter:
    sdk: flutter
  flutter_hooks: '>=0.16.0'
  freezed_annotation: '>=0.13.0-0'
  hooks_riverpod: '>=0.13.0-0'
  recase: '>=4.0.0-0'
  rxdart:
  state_notifier:
  subscription_holder: any
dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  freezed: '>=0.14.0-0'
  json_serializable: any
  pedantic_mono: any
flutter:
  uses-material-design: true
