name: example
description: A new Flutter application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  cloud_firestore:
  cloud_functions:
  cupertino_icons:
  firebase_auth:
  firebase_core:
  firebase_storage:
  firestore_ref:
    path: ..
  flutter:
    sdk: flutter
  flutter_hooks:
  freezed_annotation:
  go_router:
  hooks_riverpod:
  mono_kit:
  recase:
  rxdart:
  simple_logger:
  state_notifier:
  subscription_holder:
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  pedantic_mono:
dependency_overrides:
  hooks_riverpod: '>=2.0.0-0'
  mono_kit: '>=0.26.0-0'
flutter:
  uses-material-design: true
