# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/generated_plugin_registrant.dart
    - lib/firebase_options.dart
    - example/lib/firebase_options.dart
