name: firestore_ref
description: Firestore reference/document typed acccess helpers. You can write organized safe code by this.
version: 0.12.0-dev+3
homepage: https://github.com/mono0926/flutter_firestore_ref
environment:
  sdk: ">=2.14.0-0 <3.0.0"
dependencies:
  cloud_firestore: ">=2.0.0 <3.0.0"
  disposable_provider: ">=2.3.0 <3.0.0"
  firebase_core: ">=1.1.1 <2.0.0"
  flutter:
    sdk: flutter
  json_annotation: ">=4.0.0 <5.0.0"
  meta: ">=1.3.0 <2.0.0"
  quiver: ">=3.0.0 <4.0.0"
  rxdart: ">=0.27.0 <1.0.0"
  simple_logger: ">=1.8.0 <2.0.0"
  subscription_holder: ">=2.1.0 <3.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
flutter: